server:
  port: 8585


spring:
  application:
    name: USER-SERVICE

  # DataBase config
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true

  # Redis config
  redis:
    host: localhost
    port: 6379



